export const GET_DEMO_REQUEST = 'GET_DEMO_REQUEST';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';

export const GET_OAUTH_GITHUB_TOKEN_START = "GET_OAUTH_GITHUB_TOKEN_START";
export const GET_OAUTH_GITHUB_TOKEN_SUCCESS = "GET_OAUTH_GITHUB_TOKEN_SUCCESS";
export const GET_OAUTH_GITHUB_TOKEN_ERROR = "GET_OAUTH_GITHUB_TOKEN_ERROR";
